package com.convertor.caller;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import com.manual.coded.ComplexXml;
import com.model.codeGenerator.ComplexXmlGenerated;
import com.model.codeGenerator.StandardClassForConversion;

public class XmlToJsonUsingClassInJackson {

	public byte[] getFileBytes(String fileName) {
		try {

			return FileUtils.readFileToByteArray(new File(getClass().getClassLoader().getResource(fileName).getFile()));

		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;

	}

	public static void main(String[] args) throws IOException {
		XmlToJsonUsingClassInJackson obj = new XmlToJsonUsingClassInJackson();
		XmlMapper xmlMapper = new XmlMapper();
		ObjectMapper mapper = new ObjectMapper();
		mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

		ComplexXml realestate = xmlMapper.readValue(obj.getFileBytes("Testing.xml"), ComplexXml.class);

		String json = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(realestate);
		System.out.println(json);

		/*
		 * com.model.codeGenerator.ComplexXmlGenerated realestate1 =
		 * xmlMapper.readValue(obj.getFileBytes("Testing.xml"),
		 * com.model.codeGenerator.ComplexXmlGenerated.class); String jsonAutomated =
		 * mapper.writerWithDefaultPrettyPrinter().writeValueAsString(realestate1);
		 * System.out.
		 * println("############ JSON FROM AUTOGENERATED JAVA CLASS #####################"
		 * ); System.out.println(jsonAutomated);
		 */
		
		StandardClassForConversion gen = xmlMapper.readValue(obj.getFileBytes("Testing.xml"), StandardClassForConversion.class);
		String jsonRegen = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(gen);
		System.out.println("############ Regenerated JSON #################");
		System.out.println(jsonRegen);
		

	}

}
