<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="RealEstates">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="externalId" type="xs:string" />
				<xs:element name="ttitle" type="xs:string" />
				<xs:element name="creationDate" type="xs:string" />
				<xs:element name="lastModificationDate" type="xs:string" />
				<xs:element name="thermalCharacteristic" type="xs:string" />
				<xs:element name="energyConsumptionContainsWarmWater" type="xs:string" />
				<xs:element name="buildingEnergyRatingType" type="xs:string" />
				<xs:element name="additionalArea" type="xs:string" />
				<xs:element name="numberOfFloors" type="xs:string" />
				<xs:element name="AdditionalCosts">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="value" type="xs:string" />
							<xs:element name="currency" type="xs:string" />
							<xs:element name="marketingType" type="xs:string" />
							<xs:element name="priceIntervalType" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>