//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.04 at 06:22:31 PM SGT 
//

package com.model.codeGenerator;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

import jakarta.xml.bind.*;
import jakarta.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="externalId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="ttitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="lastModificationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="thermalCharacteristic" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="energyConsumptionContainsWarmWater" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="buildingEnergyRatingType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="additionalArea" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="numberOfFloors" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Cost"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AdditionalCosts"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                             &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="marketingType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="priceIntervalType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Take"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Take1" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Take2"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="name1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Junk"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Junkx" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Junkx1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="newField" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "externalId", "ttitle", "creationDate", "lastModificationDate",
		"thermalCharacteristic", "energyConsumptionContainsWarmWater", "buildingEnergyRatingType", "additionalArea",
		"numberOfFloors", "cost", "take", "junk", "newField" })

@JsonIgnoreProperties(ignoreUnknown = true)
@JacksonXmlRootElement(localName = "RealEstates")
public class RealEstates {

	@XmlSchemaType(name = "unsignedInt")
	protected long externalId;
	@XmlElement(required = true)
	protected String ttitle;
	@XmlElement(required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar creationDate;
	@XmlElement(required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar lastModificationDate;
	@XmlElement(required = true)
	protected BigDecimal thermalCharacteristic;
	@XmlElement(required = true)
	protected String energyConsumptionContainsWarmWater;
	@XmlElement(required = true)
	protected String buildingEnergyRatingType;
	@XmlElement(required = true)
	protected BigDecimal additionalArea;
	@XmlElement(required = true)
	protected String numberOfFloors;
	@JsonProperty("Cost")
	protected RealEstates.Cost cost;
	@JsonProperty("Take")
	protected RealEstates.Take take;
	@XmlElement(name = "Junk", required = true)
	protected RealEstates.Junk junk;
	@XmlElement(required = true)
	protected Object newField;

	/**
	 * Gets the value of the externalId property.
	 * 
	 */
	public long getExternalId() {
		return externalId;
	}

	/**
	 * Sets the value of the externalId property.
	 * 
	 */
	public void setExternalId(long value) {
		this.externalId = value;
	}

	/**
	 * Gets the value of the ttitle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTtitle() {
		return ttitle;
	}

	/**
	 * Sets the value of the ttitle property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTtitle(String value) {
		this.ttitle = value;
	}

	/**
	 * Gets the value of the creationDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getCreationDate() {
		return creationDate;
	}

	/**
	 * Sets the value of the creationDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCreationDate(XMLGregorianCalendar value) {
		this.creationDate = value;
	}

	/**
	 * Gets the value of the lastModificationDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getLastModificationDate() {
		return lastModificationDate;
	}

	/**
	 * Sets the value of the lastModificationDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setLastModificationDate(XMLGregorianCalendar value) {
		this.lastModificationDate = value;
	}

	/**
	 * Gets the value of the thermalCharacteristic property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getThermalCharacteristic() {
		return thermalCharacteristic;
	}

	/**
	 * Sets the value of the thermalCharacteristic property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setThermalCharacteristic(BigDecimal value) {
		this.thermalCharacteristic = value;
	}

	/**
	 * Gets the value of the energyConsumptionContainsWarmWater property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEnergyConsumptionContainsWarmWater() {
		return energyConsumptionContainsWarmWater;
	}

	/**
	 * Sets the value of the energyConsumptionContainsWarmWater property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setEnergyConsumptionContainsWarmWater(String value) {
		this.energyConsumptionContainsWarmWater = value;
	}

	/**
	 * Gets the value of the buildingEnergyRatingType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBuildingEnergyRatingType() {
		return buildingEnergyRatingType;
	}

	/**
	 * Sets the value of the buildingEnergyRatingType property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBuildingEnergyRatingType(String value) {
		this.buildingEnergyRatingType = value;
	}

	/**
	 * Gets the value of the additionalArea property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getAdditionalArea() {
		return additionalArea;
	}

	/**
	 * Sets the value of the additionalArea property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setAdditionalArea(BigDecimal value) {
		this.additionalArea = value;
	}

	/**
	 * Gets the value of the numberOfFloors property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumberOfFloors() {
		return numberOfFloors;
	}

	/**
	 * Sets the value of the numberOfFloors property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setNumberOfFloors(String value) {
		this.numberOfFloors = value;
	}

	/**
	 * Gets the value of the cost property.
	 * 
	 * @return possible object is {@link RealEstates.Cost }
	 * 
	 */
	public RealEstates.Cost getCost() {
		return cost;
	}

	/**
	 * Sets the value of the cost property.
	 * 
	 * @param value allowed object is {@link RealEstates.Cost }
	 * 
	 */
	public void setCost(RealEstates.Cost value) {
		this.cost = value;
	}

	/**
	 * Gets the value of the take property.
	 * 
	 * @return possible object is {@link RealEstates.Take }
	 * 
	 */
	public RealEstates.Take getTake() {
		return take;
	}

	/**
	 * Sets the value of the take property.
	 * 
	 * @param value allowed object is {@link RealEstates.Take }
	 * 
	 */
	public void setTake(RealEstates.Take value) {
		this.take = value;
	}

	/**
	 * Gets the value of the junk property.
	 * 
	 * @return possible object is {@link RealEstates.Junk }
	 * 
	 */
	public RealEstates.Junk getJunk() {
		return junk;
	}

	/**
	 * Sets the value of the junk property.
	 * 
	 * @param value allowed object is {@link RealEstates.Junk }
	 * 
	 */
	public void setJunk(RealEstates.Junk value) {
		this.junk = value;
	}

	/**
	 * Gets the value of the newField property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getNewField() {
		return newField;
	}

	/**
	 * Sets the value of the newField property.
	 * 
	 * @param value allowed object is {@link Object }
	 * 
	 */
	public void setNewField(Object value) {
		this.newField = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="AdditionalCosts"&gt;
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                 &lt;sequence&gt;
	 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
	 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="marketingType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="priceIntervalType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                 &lt;/sequence&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	/*
	 * @XmlAccessorType(XmlAccessType.FIELD)
	 * 
	 * @XmlType(name = "", propOrder = { "additionalCosts" })
	 */
	public static class Cost {

		@JacksonXmlElementWrapper(useWrapping = false)
		@JacksonXmlProperty(localName = "AdditionalCosts")
		protected List<RealEstates.Cost.AdditionalCosts> additionalCosts;

		/**
		 * Gets the value of the additionalCosts property.
		 * 
		 * @return possible object is {@link RealEstates.Cost.AdditionalCosts }
		 * 
		 */
		public List<RealEstates.Cost.AdditionalCosts> getAdditionalCosts() {
			return additionalCosts;
		}

		/**
		 * Sets the value of the additionalCosts property.
		 * 
		 * @param value allowed object is {@link RealEstates.Cost.AdditionalCosts }
		 * 
		 */
		public void setAdditionalCosts(List<RealEstates.Cost.AdditionalCosts> value) {
			this.additionalCosts = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *       &lt;sequence&gt;
		 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
		 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="marketingType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="priceIntervalType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *       &lt;/sequence&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 * 
		 * 
		 */
		/*
		 * @XmlAccessorType(XmlAccessType.FIELD)
		 * 
		 * @XmlType(name = "", propOrder = { "value", "currency", "marketingType",
		 * "priceIntervalType" })
		 */
		public static class AdditionalCosts {

			// @XmlElement(required = true)
			protected BigDecimal value;
			// @XmlElement(required = true)
			protected String currency;
			// @XmlElement(required = true)
			protected String marketingType;
			// @XmlElement(required = true)
			protected String priceIntervalType;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link BigDecimal }
			 * 
			 */
			public BigDecimal getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value allowed object is {@link BigDecimal }
			 * 
			 */
			public void setValue(BigDecimal value) {
				this.value = value;
			}

			/**
			 * Gets the value of the currency property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCurrency() {
				return currency;
			}

			/**
			 * Sets the value of the currency property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setCurrency(String value) {
				this.currency = value;
			}

			/**
			 * Gets the value of the marketingType property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMarketingType() {
				return marketingType;
			}

			/**
			 * Sets the value of the marketingType property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setMarketingType(String value) {
				this.marketingType = value;
			}

			/**
			 * Gets the value of the priceIntervalType property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPriceIntervalType() {
				return priceIntervalType;
			}

			/**
			 * Sets the value of the priceIntervalType property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setPriceIntervalType(String value) {
				this.priceIntervalType = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="Junkx" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="Junkx1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "junkx", "junkx1" })
	public static class Junk {

		@XmlElement(name = "Junkx", required = true)
		protected String junkx;
		@XmlElement(name = "Junkx1", required = true)
		protected String junkx1;

		/**
		 * Gets the value of the junkx property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getJunkx() {
			return junkx;
		}

		/**
		 * Sets the value of the junkx property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setJunkx(String value) {
			this.junkx = value;
		}

		/**
		 * Gets the value of the junkx1 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getJunkx1() {
			return junkx1;
		}

		/**
		 * Sets the value of the junkx1 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setJunkx1(String value) {
			this.junkx1 = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="Take1" maxOccurs="unbounded"&gt;
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                 &lt;sequence&gt;
	 *                   &lt;element name="Take2"&gt;
	 *                     &lt;complexType&gt;
	 *                       &lt;complexContent&gt;
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                           &lt;sequence&gt;
	 *                             &lt;element name="name1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                             &lt;element name="name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
	 *                           &lt;/sequence&gt;
	 *                         &lt;/restriction&gt;
	 *                       &lt;/complexContent&gt;
	 *                     &lt;/complexType&gt;
	 *                   &lt;/element&gt;
	 *                 &lt;/sequence&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "take1" })
	public static class Take {

		@JacksonXmlElementWrapper(useWrapping = false)
		@JacksonXmlProperty(localName = "Take1")
		protected List<RealEstates.Take.Take1> take1;

		/**
		 * Gets the value of the take1 property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the Jakarta XML Binding object. This is why there is not a
		 * <CODE>set</CODE> method for the take1 property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getTake1().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link RealEstates.Take.Take1 }
		 * 
		 * 
		 */
		public List<RealEstates.Take.Take1> getTake1() {
			if (take1 == null) {
				take1 = new ArrayList<RealEstates.Take.Take1>();
			}
			return this.take1;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *       &lt;sequence&gt;
		 *         &lt;element name="Take2"&gt;
		 *           &lt;complexType&gt;
		 *             &lt;complexContent&gt;
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *                 &lt;sequence&gt;
		 *                   &lt;element name="name1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *                   &lt;element name="name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
		 *                 &lt;/sequence&gt;
		 *               &lt;/restriction&gt;
		 *             &lt;/complexContent&gt;
		 *           &lt;/complexType&gt;
		 *         &lt;/element&gt;
		 *       &lt;/sequence&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "take2" })
		public static class Take1 {
			
			  
			  @JacksonXmlElementWrapper(useWrapping = false)  
			  @JacksonXmlProperty(localName = "Take2")
			 protected List<RealEstates.Take.Take1.Take2> take2;

			/**
			 * Gets the value of the take2 property.
			 * 
			 * @return possible object is {@link RealEstates.Take.Take1 .Take2 }
			 * 
			 */
			public List<RealEstates.Take.Take1.Take2> getTake2() {
				return take2;
			}

			/**
			 * Sets the value of the take2 property.
			 * 
			 * @param value allowed object is {@link RealEstates.Take.Take1 .Take2 }
			 * 
			 */
			public void setTake2(List<RealEstates.Take.Take1.Take2> value) {
				this.take2 = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content contained within
			 * this class.
			 * 
			 * <pre>
			 * &lt;complexType&gt;
			 *   &lt;complexContent&gt;
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
			 *       &lt;sequence&gt;
			 *         &lt;element name="name1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
			 *         &lt;element name="name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
			 *       &lt;/sequence&gt;
			 *     &lt;/restriction&gt;
			 *   &lt;/complexContent&gt;
			 * &lt;/complexType&gt;
			 * </pre>
			 * 
			 * 
			 */
			/*
			 * @XmlAccessorType(XmlAccessType.FIELD)
			 * 
			 * @XmlType(name = "", propOrder = { "name1", "name2" })
			 */
			@JsonIgnoreProperties(ignoreUnknown = true)
			public static class Take2 {

				protected String name1;
				protected String name2;

				/**
				 * Gets the value of the name1 property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getName1() {
					return name1;
				}

				/**
				 * Sets the value of the name1 property.
				 * 
				 * @param value allowed object is {@link String }
				 * 
				 */
				public void setName1(String value) {
					this.name1 = value;
				}

				/**
				 * Gets the value of the name2 property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getName2() {
					return name2;
				}

				/**
				 * Sets the value of the name2 property.
				 * 
				 * @param value allowed object is {@link String }
				 * 
				 */
				public void setName2(String value) {
					this.name2 = value;
				}

			}

		}

	}

}
