//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.18 at 06:13:07 PM SGT 
//


package com.model.codeGenerator;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="externalId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="ttitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="lastModificationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="thermalCharacteristic" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="energyConsumptionContainsWarmWater" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="buildingEnergyRatingType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="additionalArea" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="numberOfFloors" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Cost"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AdditionalCosts" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                             &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="marketingType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="priceIntervalType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Take"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Take1" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Take2"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="name1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="name3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Junk"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Junkx" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Junkx1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="newField" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="Instances"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Instance"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="REGION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="TESTED" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                             &lt;element name="SubInstances"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="SubInstance" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="branchName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="branchId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *                                                 &lt;element name="MINUTEDETAILS" minOccurs="0"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;complexContent&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                         &lt;sequence&gt;
 *                                                           &lt;element name="LEV1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                           &lt;element name="LEV2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                           &lt;element name="LEVS"&gt;
 *                                                             &lt;complexType&gt;
 *                                                               &lt;complexContent&gt;
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                                   &lt;sequence&gt;
 *                                                                     &lt;element name="LEV3"&gt;
 *                                                                       &lt;complexType&gt;
 *                                                                         &lt;complexContent&gt;
 *                                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                                             &lt;sequence&gt;
 *                                                                               &lt;element name="low1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                                               &lt;element name="low2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                                             &lt;/sequence&gt;
 *                                                                           &lt;/restriction&gt;
 *                                                                         &lt;/complexContent&gt;
 *                                                                       &lt;/complexType&gt;
 *                                                                     &lt;/element&gt;
 *                                                                   &lt;/sequence&gt;
 *                                                                 &lt;/restriction&gt;
 *                                                               &lt;/complexContent&gt;
 *                                                             &lt;/complexType&gt;
 *                                                           &lt;/element&gt;
 *                                                         &lt;/sequence&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/complexContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "externalId",
    "ttitle",
    "creationDate",
    "lastModificationDate",
    "thermalCharacteristic",
    "energyConsumptionContainsWarmWater",
    "buildingEnergyRatingType",
    "additionalArea",
    "numberOfFloors",
    "cost",
    "take",
    "junk",
    "newField",
    "instances"
})
//@XmlRootElement(name = "RealEstates")
@JsonIgnoreProperties(ignoreUnknown = true)
@JacksonXmlRootElement(localName = "RealEstates")
public class StandardClassForConversion {

   // @XmlSchemaType(name = "unsignedInt")
	@JacksonXmlProperty(localName="externalId")
    protected long externalId;
    //@XmlElement(required = true)
	@JacksonXmlProperty(localName="title")
    protected String ttitle;
	/*
	 * @XmlElement(required = true)
	 * 
	 * @XmlSchemaType(name = "dateTime")
	 */
	@JacksonXmlProperty(localName="creationDate")
    protected XMLGregorianCalendar creationDate;
	/*
	 * @XmlElement(required = true)
	 * 
	 * @XmlSchemaType(name = "dateTime")
	 */
	@JacksonXmlProperty(localName="lastModificationDate")
    protected XMLGregorianCalendar lastModificationDate;
	/* @XmlElement(required = true) */
	@JacksonXmlProperty(localName="thermalCharacteristic")
    protected BigDecimal thermalCharacteristic;
	/* @XmlElement(required = true) */
	@JacksonXmlProperty(localName="energyConsumptionContainsWarmWater")
    protected String energyConsumptionContainsWarmWater;
    @XmlElement(required = true)
    protected String buildingEnergyRatingType;
    @XmlElement(required = true)
    protected BigDecimal additionalArea;
    @XmlElement(required = true)
    protected String numberOfFloors;
    //@XmlElement(name = "Cost", required = true)
    @JsonProperty("Cost")
    protected StandardClassForConversion.Cost cost;
    //@XmlElement(name = "Take", required = true)
    @JsonProperty("Take")
    protected StandardClassForConversion.Take take;
    //@XmlElement(name = "Junk", required = true)
    @JsonProperty("Junk")
    protected StandardClassForConversion.Junk junk;
    @XmlElement(required = true)
    protected Object newField;
    //@XmlElement(name = "Instances", required = true)
    @JsonProperty("Instances")
    protected StandardClassForConversion.Instances instances;

    /**
     * Gets the value of the externalId property.
     * 
     */
    public long getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     * 
     */
    public void setExternalId(long value) {
        this.externalId = value;
    }

    /**
     * Gets the value of the ttitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTtitle() {
        return ttitle;
    }

    /**
     * Sets the value of the ttitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTtitle(String value) {
        this.ttitle = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the lastModificationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModificationDate() {
        return lastModificationDate;
    }

    /**
     * Sets the value of the lastModificationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModificationDate(XMLGregorianCalendar value) {
        this.lastModificationDate = value;
    }

    /**
     * Gets the value of the thermalCharacteristic property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getThermalCharacteristic() {
        return thermalCharacteristic;
    }

    /**
     * Sets the value of the thermalCharacteristic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setThermalCharacteristic(BigDecimal value) {
        this.thermalCharacteristic = value;
    }

    /**
     * Gets the value of the energyConsumptionContainsWarmWater property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnergyConsumptionContainsWarmWater() {
        return energyConsumptionContainsWarmWater;
    }

    /**
     * Sets the value of the energyConsumptionContainsWarmWater property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnergyConsumptionContainsWarmWater(String value) {
        this.energyConsumptionContainsWarmWater = value;
    }

    /**
     * Gets the value of the buildingEnergyRatingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingEnergyRatingType() {
        return buildingEnergyRatingType;
    }

    /**
     * Sets the value of the buildingEnergyRatingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingEnergyRatingType(String value) {
        this.buildingEnergyRatingType = value;
    }

    /**
     * Gets the value of the additionalArea property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdditionalArea() {
        return additionalArea;
    }

    /**
     * Sets the value of the additionalArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdditionalArea(BigDecimal value) {
        this.additionalArea = value;
    }

    /**
     * Gets the value of the numberOfFloors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfFloors() {
        return numberOfFloors;
    }

    /**
     * Sets the value of the numberOfFloors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfFloors(String value) {
        this.numberOfFloors = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link StandardClassForConversion.Cost }
     *     
     */
    public StandardClassForConversion.Cost getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardClassForConversion.Cost }
     *     
     */
    public void setCost(StandardClassForConversion.Cost value) {
        this.cost = value;
    }

    /**
     * Gets the value of the take property.
     * 
     * @return
     *     possible object is
     *     {@link StandardClassForConversion.Take }
     *     
     */
    public StandardClassForConversion.Take getTake() {
        return take;
    }

    /**
     * Sets the value of the take property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardClassForConversion.Take }
     *     
     */
    public void setTake(StandardClassForConversion.Take value) {
        this.take = value;
    }

    /**
     * Gets the value of the junk property.
     * 
     * @return
     *     possible object is
     *     {@link StandardClassForConversion.Junk }
     *     
     */
    public StandardClassForConversion.Junk getJunk() {
        return junk;
    }

    /**
     * Sets the value of the junk property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardClassForConversion.Junk }
     *     
     */
    public void setJunk(StandardClassForConversion.Junk value) {
        this.junk = value;
    }

    /**
     * Gets the value of the newField property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNewField() {
        return newField;
    }

    /**
     * Sets the value of the newField property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNewField(Object value) {
        this.newField = value;
    }

    /**
     * Gets the value of the instances property.
     * 
     * @return
     *     possible object is
     *     {@link StandardClassForConversion.Instances }
     *     
     */
    public StandardClassForConversion.Instances getInstances() {
        return instances;
    }

    /**
     * Sets the value of the instances property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardClassForConversion.Instances }
     *     
     */
    public void setInstances(StandardClassForConversion.Instances value) {
        this.instances = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="AdditionalCosts" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="marketingType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="priceIntervalType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
	/*
	 * @XmlAccessorType(XmlAccessType.FIELD)
	 * 
	 * @XmlType(name = "", propOrder = { "additionalCosts" })
	 */
    public static class Cost {

        //@XmlElement(name = "AdditionalCosts", required = true)
    	@JacksonXmlElementWrapper(useWrapping = false)
    	@JacksonXmlProperty(localName="AdditionalCosts")
        protected List<StandardClassForConversion.Cost.AdditionalCosts> additionalCosts;

        /**
         * Gets the value of the additionalCosts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the additionalCosts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdditionalCosts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StandardClassForConversion.Cost.AdditionalCosts }
         * 
         * 
         */
        public List<StandardClassForConversion.Cost.AdditionalCosts> getAdditionalCosts() {
            return this.additionalCosts;
        }
        
        public void setAdditionalCosts(List<AdditionalCosts> additionalCosts) {
            this.additionalCosts=additionalCosts;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
         *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="marketingType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="priceIntervalType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value",
            "currency",
            "marketingType",
            "priceIntervalType"
        })
        public static class AdditionalCosts {

            @XmlElement(required = true)
            protected BigDecimal value;
            @XmlElement(required = true)
            protected String currency;
            @XmlElement(required = true)
            protected String marketingType;
            @XmlElement(required = true)
            protected String priceIntervalType;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            /**
             * Gets the value of the marketingType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMarketingType() {
                return marketingType;
            }

            /**
             * Sets the value of the marketingType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMarketingType(String value) {
                this.marketingType = value;
            }

            /**
             * Gets the value of the priceIntervalType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPriceIntervalType() {
                return priceIntervalType;
            }

            /**
             * Sets the value of the priceIntervalType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPriceIntervalType(String value) {
                this.priceIntervalType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Instance"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="REGION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="TESTED" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *                   &lt;element name="SubInstances"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="SubInstance" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="branchName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="branchId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
     *                                       &lt;element name="MINUTEDETAILS" minOccurs="0"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;sequence&gt;
     *                                                 &lt;element name="LEV1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                 &lt;element name="LEV2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                 &lt;element name="LEVS"&gt;
     *                                                   &lt;complexType&gt;
     *                                                     &lt;complexContent&gt;
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                                         &lt;sequence&gt;
     *                                                           &lt;element name="LEV3"&gt;
     *                                                             &lt;complexType&gt;
     *                                                               &lt;complexContent&gt;
     *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                                                   &lt;sequence&gt;
     *                                                                     &lt;element name="low1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                                     &lt;element name="low2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                                   &lt;/sequence&gt;
     *                                                                 &lt;/restriction&gt;
     *                                                               &lt;/complexContent&gt;
     *                                                             &lt;/complexType&gt;
     *                                                           &lt;/element&gt;
     *                                                         &lt;/sequence&gt;
     *                                                       &lt;/restriction&gt;
     *                                                     &lt;/complexContent&gt;
     *                                                   &lt;/complexType&gt;
     *                                                 &lt;/element&gt;
     *                                               &lt;/sequence&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
	/*
	 * @XmlAccessorType(XmlAccessType.FIELD)
	 * 
	 * @XmlType(name = "", propOrder = { "instance" })
	 */
    public static class Instances {

        //@XmlElement(name = "Instance", required = true)
    	@JacksonXmlElementWrapper(useWrapping = false)
        @JacksonXmlProperty(localName = "Instance")
        protected List<StandardClassForConversion.Instances.Instance> instance;

        /**
         * Gets the value of the instance property.
         * 
         * @return
         *     possible object is
         *     {@link StandardClassForConversion.Instances.Instance }
         *     
         */
        public List<StandardClassForConversion.Instances.Instance> getInstance() {
            return instance;
        }

        /**
         * Sets the value of the instance property.
         * 
         * @param value
         *     allowed object is
         *     {@link StandardClassForConversion.Instances.Instance }
         *     
         */
        public void setInstance(List<StandardClassForConversion.Instances.Instance> value) {
            this.instance = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="REGION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="TESTED" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
         *         &lt;element name="SubInstances"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="SubInstance" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="branchName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="branchId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
         *                             &lt;element name="MINUTEDETAILS" minOccurs="0"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;sequence&gt;
         *                                       &lt;element name="LEV1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                       &lt;element name="LEV2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                       &lt;element name="LEVS"&gt;
         *                                         &lt;complexType&gt;
         *                                           &lt;complexContent&gt;
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                               &lt;sequence&gt;
         *                                                 &lt;element name="LEV3"&gt;
         *                                                   &lt;complexType&gt;
         *                                                     &lt;complexContent&gt;
         *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                                         &lt;sequence&gt;
         *                                                           &lt;element name="low1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                                           &lt;element name="low2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                                         &lt;/sequence&gt;
         *                                                       &lt;/restriction&gt;
         *                                                     &lt;/complexContent&gt;
         *                                                   &lt;/complexType&gt;
         *                                                 &lt;/element&gt;
         *                                               &lt;/sequence&gt;
         *                                             &lt;/restriction&gt;
         *                                           &lt;/complexContent&gt;
         *                                         &lt;/complexType&gt;
         *                                       &lt;/element&gt;
         *                                     &lt;/sequence&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
		/*
		 * @XmlAccessorType(XmlAccessType.FIELD)
		 * 
		 * @XmlType(name = "", propOrder = { "name", "region", "tested", "subInstances"
		 * })
		 */
        @JsonIgnoreProperties(ignoreUnknown = true)
        public static class Instance {

            @XmlElement(name = "NAME", required = true)
        	//@JacksonXmlProperty(localName="NAME")
            protected String name;
            @XmlElement(name = "REGION", required = true)
        	//@JacksonXmlProperty(localName="NAME")
            protected String region;
            @XmlElement(name = "TESTED", required = true)
        	//@JacksonXmlProperty(localName="NAME")
            protected Object tested;
            //@XmlElement(name = "SubInstances", required = true)
        	@JacksonXmlElementWrapper(useWrapping=false)
        	@JacksonXmlProperty(localName="SubInstances")
            protected List<StandardClassForConversion.Instances.Instance.SubInstances> subInstances;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNAME() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNAME(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the region property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getREGION() {
                return region;
            }

            /**
             * Sets the value of the region property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setREGION(String value) {
                this.region = value;
            }

            /**
             * Gets the value of the tested property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getTESTED() {
                return tested;
            }

            /**
             * Sets the value of the tested property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setTESTED(Object value) {
                this.tested = value;
            }

            /**
             * Gets the value of the subInstances property.
             * 
             * @return
             *     possible object is
             *     {@link StandardClassForConversion.Instances.Instance.SubInstances }
             *     
             */
            public List<StandardClassForConversion.Instances.Instance.SubInstances> getSubInstances() {
                return subInstances;
            }

            /**
             * Sets the value of the subInstances property.
             * 
             * @param value
             *     allowed object is
             *     {@link StandardClassForConversion.Instances.Instance.SubInstances }
             *     
             */
            public void setSubInstances(List<StandardClassForConversion.Instances.Instance.SubInstances> value) {
                this.subInstances = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="SubInstance" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="branchName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="branchId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
             *                   &lt;element name="MINUTEDETAILS" minOccurs="0"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;sequence&gt;
             *                             &lt;element name="LEV1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                             &lt;element name="LEV2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                             &lt;element name="LEVS"&gt;
             *                               &lt;complexType&gt;
             *                                 &lt;complexContent&gt;
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                                     &lt;sequence&gt;
             *                                       &lt;element name="LEV3"&gt;
             *                                         &lt;complexType&gt;
             *                                           &lt;complexContent&gt;
             *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                                               &lt;sequence&gt;
             *                                                 &lt;element name="low1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                                                 &lt;element name="low2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                                               &lt;/sequence&gt;
             *                                             &lt;/restriction&gt;
             *                                           &lt;/complexContent&gt;
             *                                         &lt;/complexType&gt;
             *                                       &lt;/element&gt;
             *                                     &lt;/sequence&gt;
             *                                   &lt;/restriction&gt;
             *                                 &lt;/complexContent&gt;
             *                               &lt;/complexType&gt;
             *                             &lt;/element&gt;
             *                           &lt;/sequence&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
			/*
			 * @XmlAccessorType(XmlAccessType.FIELD)
			 * 
			 * @XmlType(name = "", propOrder = { "subInstance" })
			 */
            @JsonIgnoreProperties(ignoreUnknown = true)
            public static class SubInstances {

                //@XmlElement(name = "SubInstance", required = true)
            	@JacksonXmlElementWrapper(useWrapping=false)
            	@JacksonXmlProperty(localName="SubInstance")
                protected List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance> subInstance;

                /**
                 * Gets the value of the subInstance property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a <CODE>set</CODE> method for the subInstance property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getSubInstance().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link StandardClassForConversion.Instances.Instance.SubInstances.SubInstance }
                 * 
                 * 
                 */
                public List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance> getSubInstance() {
                    if (subInstance == null) {
                        subInstance = new ArrayList<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance>();
                    }
                    return this.subInstance;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="branchName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="branchId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
                 *         &lt;element name="MINUTEDETAILS" minOccurs="0"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;sequence&gt;
                 *                   &lt;element name="LEV1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                   &lt;element name="LEV2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                   &lt;element name="LEVS"&gt;
                 *                     &lt;complexType&gt;
                 *                       &lt;complexContent&gt;
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                           &lt;sequence&gt;
                 *                             &lt;element name="LEV3"&gt;
                 *                               &lt;complexType&gt;
                 *                                 &lt;complexContent&gt;
                 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                                     &lt;sequence&gt;
                 *                                       &lt;element name="low1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                                       &lt;element name="low2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                                     &lt;/sequence&gt;
                 *                                   &lt;/restriction&gt;
                 *                                 &lt;/complexContent&gt;
                 *                               &lt;/complexType&gt;
                 *                             &lt;/element&gt;
                 *                           &lt;/sequence&gt;
                 *                         &lt;/restriction&gt;
                 *                       &lt;/complexContent&gt;
                 *                     &lt;/complexType&gt;
                 *                   &lt;/element&gt;
                 *                 &lt;/sequence&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
				/*
				 * @XmlAccessorType(XmlAccessType.FIELD)
				 * 
				 * @XmlType(name = "", propOrder = { "branchName", "branchId", "minutedetails"
				 * })
				 */
                @JsonIgnoreProperties(ignoreUnknown = true)
                public static class SubInstance {

                    @XmlElement(required = true)
                    protected String branchName;
                    @XmlSchemaType(name = "unsignedByte")
                    protected short branchId;
                    //@XmlElement(name = "MINUTEDETAILS")
                    @JacksonXmlElementWrapper(useWrapping=false)
                    @JacksonXmlProperty(localName="MINUTEDETAILS")
                    protected List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS> minutedetails;

                    /**
                     * Gets the value of the branchName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBranchName() {
                        return branchName;
                    }

                    /**
                     * Sets the value of the branchName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBranchName(String value) {
                        this.branchName = value;
                    }

                    /**
                     * Gets the value of the branchId property.
                     * 
                     */
                    public short getBranchId() {
                        return branchId;
                    }

                    /**
                     * Sets the value of the branchId property.
                     * 
                     */
                    public void setBranchId(short value) {
                        this.branchId = value;
                    }

                    /**
                     * Gets the value of the minutedetails property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS }
                     *     
                     */
                    public List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS> getMINUTEDETAILS() {
                        return minutedetails;
                    }

                    /**
                     * Sets the value of the minutedetails property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS }
                     *     
                     */
                    public void setMINUTEDETAILS(List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS> value) {
                        this.minutedetails = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;sequence&gt;
                     *         &lt;element name="LEV1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *         &lt;element name="LEV2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *         &lt;element name="LEVS"&gt;
                     *           &lt;complexType&gt;
                     *             &lt;complexContent&gt;
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *                 &lt;sequence&gt;
                     *                   &lt;element name="LEV3"&gt;
                     *                     &lt;complexType&gt;
                     *                       &lt;complexContent&gt;
                     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *                           &lt;sequence&gt;
                     *                             &lt;element name="low1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *                             &lt;element name="low2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *                           &lt;/sequence&gt;
                     *                         &lt;/restriction&gt;
                     *                       &lt;/complexContent&gt;
                     *                     &lt;/complexType&gt;
                     *                   &lt;/element&gt;
                     *                 &lt;/sequence&gt;
                     *               &lt;/restriction&gt;
                     *             &lt;/complexContent&gt;
                     *           &lt;/complexType&gt;
                     *         &lt;/element&gt;
                     *       &lt;/sequence&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
					/*
					 * @XmlAccessorType(XmlAccessType.FIELD)
					 * 
					 * @XmlType(name = "", propOrder = { "lev1", "lev2", "levs" })
					 */
                    @JsonIgnoreProperties(ignoreUnknown = true)
                    public static class MINUTEDETAILS {

                        //@XmlElement(name = "LEV1", required = true)
                    	@JsonProperty("LEV1")
                        protected String lev1;
                        //@XmlElement(name = "LEV2", required = true)
                    	@JsonProperty("LEV2")
                        protected String lev2;
                        //@XmlElement(name = "LEVS", required = true)
                        @JacksonXmlElementWrapper(useWrapping=false)
                        @JacksonXmlProperty(localName="LEVS")
                        protected List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS.LEVS> levs;

                        /**
                         * Gets the value of the lev1 property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getLEV1() {
                            return lev1;
                        }

                        /**
                         * Sets the value of the lev1 property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setLEV1(String value) {
                            this.lev1 = value;
                        }

                        /**
                         * Gets the value of the lev2 property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getLEV2() {
                            return lev2;
                        }

                        /**
                         * Sets the value of the lev2 property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setLEV2(String value) {
                            this.lev2 = value;
                        }

                        /**
                         * Gets the value of the levs property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS.LEVS }
                         *     
                         */
                        public List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS.LEVS> getLEVS() {
                            return levs;
                        }

                        /**
                         * Sets the value of the levs property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS.LEVS }
                         *     
                         */
                        public void setLEVS(List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS.LEVS> value) {
                            this.levs = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType&gt;
                         *   &lt;complexContent&gt;
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                         *       &lt;sequence&gt;
                         *         &lt;element name="LEV3"&gt;
                         *           &lt;complexType&gt;
                         *             &lt;complexContent&gt;
                         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                         *                 &lt;sequence&gt;
                         *                   &lt;element name="low1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                         *                   &lt;element name="low2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                         *                 &lt;/sequence&gt;
                         *               &lt;/restriction&gt;
                         *             &lt;/complexContent&gt;
                         *           &lt;/complexType&gt;
                         *         &lt;/element&gt;
                         *       &lt;/sequence&gt;
                         *     &lt;/restriction&gt;
                         *   &lt;/complexContent&gt;
                         * &lt;/complexType&gt;
                         * </pre>
                         * 
                         * 
                         */
						/*
						 * @XmlAccessorType(XmlAccessType.FIELD)
						 * 
						 * @XmlType(name = "", propOrder = { "lev3" })
						 */
                        @JsonIgnoreProperties(ignoreUnknown = true)
                        public static class LEVS {

                            //@XmlElement(name = "LEV3", required = true)
                            @JacksonXmlElementWrapper(useWrapping = false)
                            @JacksonXmlProperty(localName="LEV3")
                            protected List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS.LEVS.LEV3> lev3;

                            /**
                             * Gets the value of the lev3 property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS.LEVS.LEV3 }
                             *     
                             */
                            public List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS.LEVS.LEV3> getLEV3() {
                                return lev3;
                            }

                            /**
                             * Sets the value of the lev3 property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS.LEVS.LEV3 }
                             *     
                             */
                            public void setLEV3(List<StandardClassForConversion.Instances.Instance.SubInstances.SubInstance.MINUTEDETAILS.LEVS.LEV3> value) {
                                this.lev3 = value;
                            }


                            /**
                             * <p>Java class for anonymous complex type.
                             * 
                             * <p>The following schema fragment specifies the expected content contained within this class.
                             * 
                             * <pre>
                             * &lt;complexType&gt;
                             *   &lt;complexContent&gt;
                             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                             *       &lt;sequence&gt;
                             *         &lt;element name="low1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                             *         &lt;element name="low2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                             *       &lt;/sequence&gt;
                             *     &lt;/restriction&gt;
                             *   &lt;/complexContent&gt;
                             * &lt;/complexType&gt;
                             * </pre>
                             * 
                             * 
                             */
							/*
							 * @XmlAccessorType(XmlAccessType.FIELD)
							 * 
							 * @XmlType(name = "", propOrder = { "low1", "low2" })
							 */
                            public static class LEV3 {

                                //@XmlElement(required = true)
                            	@JsonProperty("low1")
                                protected String low1;
                            	@JsonProperty("low2")
                                //@XmlElement(required = true)
                                protected String low2;

                                /**
                                 * Gets the value of the low1 property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getLow1() {
                                    return low1;
                                }

                                /**
                                 * Sets the value of the low1 property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setLow1(String value) {
                                    this.low1 = value;
                                }

                                /**
                                 * Gets the value of the low2 property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getLow2() {
                                    return low2;
                                }

                                /**
                                 * Sets the value of the low2 property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setLow2(String value) {
                                    this.low2 = value;
                                }

                            }

                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Junkx" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Junkx1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
	/*
	 * @XmlAccessorType(XmlAccessType.FIELD)
	 * 
	 * @XmlType(name = "", propOrder = { "junkx", "junkx1" })
	 */
    public static class Junk {

        //@XmlElement(name = "Junkx", required = true)
    	@JacksonXmlProperty(localName="Junkx")
        protected String junkx;
        //@XmlElement(name = "Junkx1", required = true)
    	@JacksonXmlProperty(localName="Junkx1")
        protected String junkx1;

        /**
         * Gets the value of the junkx property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJunkx() {
            return junkx;
        }

        /**
         * Sets the value of the junkx property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJunkx(String value) {
            this.junkx = value;
        }

        /**
         * Gets the value of the junkx1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJunkx1() {
            return junkx1;
        }

        /**
         * Sets the value of the junkx1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJunkx1(String value) {
            this.junkx1 = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Take1" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Take2"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="name1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="name3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
	
	@XmlAccessorType(XmlAccessType.FIELD) 
    @XmlType(name = "", propOrder = { "take1" })
    public static class Take {

        //@XmlElement(name = "Take1", required = true)
		@JacksonXmlElementWrapper(useWrapping=false)
		@JacksonXmlProperty(localName="Take1")
        protected List<StandardClassForConversion.Take.Take1> take1;

        /**
         * Gets the value of the take1 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the take1 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTake1().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StandardClassForConversion.Take.Take1 }
         * 
         * 
         */
        public List<StandardClassForConversion.Take.Take1> getTake1() {
            return this.take1;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Take2"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="name1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="name3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
		/*
		 * @XmlAccessorType(XmlAccessType.FIELD)
		 * 
		 * @XmlType(name = "", propOrder = { "take2" })
		 */
        public static class Take1 {

            //@XmlElement(name = "Take2", required = true)
        	@JacksonXmlElementWrapper(useWrapping=false)
        	@JacksonXmlProperty(localName="Take2")
            protected List<StandardClassForConversion.Take.Take1.Take2> take2;

            /**
             * Gets the value of the take2 property.
             * 
             * @return
             *     possible object is
             *     {@link StandardClassForConversion.Take.Take1 .Take2 }
             *     
             */
            public List<StandardClassForConversion.Take.Take1.Take2> getTake2() {
                return take2;
            }

            /**
             * Sets the value of the take2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link StandardClassForConversion.Take.Take1 .Take2 }
             *     
             */
            public void setTake2(List<StandardClassForConversion.Take.Take1.Take2> value) {
                this.take2 = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="name1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="name3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name1",
                "name2",
                "name3"
            })
            public static class Take2 {

                @XmlElement(required = true)
                protected String name1;
                protected String name2;
                protected String name3;

                /**
                 * Gets the value of the name1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName1() {
                    return name1;
                }

                /**
                 * Sets the value of the name1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName1(String value) {
                    this.name1 = value;
                }

                /**
                 * Gets the value of the name2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName2() {
                    return name2;
                }

                /**
                 * Sets the value of the name2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName2(String value) {
                    this.name2 = value;
                }

                /**
                 * Gets the value of the name3 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName3() {
                    return name3;
                }

                /**
                 * Sets the value of the name3 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName3(String value) {
                    this.name3 = value;
                }

            }

        }

    }

}
